varReference:
- path: spec/storageClassName
  kind: PersistentVolumeClaim
- path: spec/resources/requests/storage
  kind: PersistentVolumeClaim
- path: metadata/name
  kind: PersistentVolumeClaim
- path: metadata/name
  kind: StorageClass
- path: parameters/type
  kind: StorageClass