apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-viewer-template
data:
  viewer-tensorboard-template.json: |
    {
        "spec": {
            "containers": [
                {
                    "env": [
                        {
                            "name": "AWS_ACCESS_KEY_ID",
                            "valueFrom": {
                                "secretKeyRef": {
                                    "name": "$(awsSecretName)",
                                    "key": "$(awsAccessKeySecretKey)"
                                }
                            }
                        },
                        {
                            "name": "AWS_SECRET_ACCESS_KEY",
                            "valueFrom": {
                                "secretKeyRef": {
                                    "name": "$(awsSecretName)",
                                    "key": "$(awsSecretKeySecretKey)"
                                }
                            }
                        },
                        {
                            "name": "AWS_REGION",
                            "value": "ap-southeast-1"
                        }
                    ]
                }
            ]
        }
    }